In [1]:
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv('loan_data.csv')
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [3]:
X=df.drop(columns='loan_status')
y=df.loan_status

In [4]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,train_size=0.8,random_state=42)

In [5]:
# num_cols=X.select_dtypes(include='number').columns
obj_cols=X.select_dtypes(include='object').columns

C:\Users\DELL\AppData\Local\Temp\ipykernel_14960\1865124758.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols=X.select_dtypes(include='object').columns

In [6]:
X[obj_cols].nunique()

person_gender                     2
person_education                  5
person_home_ownership             4
loan_intent                       6
previous_loan_defaults_on_file    2
dtype: int64

In [7]:
X['person_education'].unique()

<ArrowStringArray>
['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate']
Length: 5, dtype: str

In [8]:
order=['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate']

In [9]:
preprocessing=ColumnTransformer(
    transformers=[
        ('onehot_encoder',OneHotEncoder(handle_unknown='ignore'),obj_cols.drop('person_education')),
        ('ordinal_encoder',OrdinalEncoder(categories=[order],handle_unknown='use_encoded_value',unknown_value=-1),['person_education'])
    ],remainder='passthrough'
)

In [10]:
main_pipeline=Pipeline(
    steps=[
        ('preprocessing',preprocessing),
        ('model',LogisticRegression(random_state=42))
    ]
)

In [11]:
grid_search_cv = GridSearchCV(
    estimator=main_pipeline,
    param_grid={
        'model__C': [0.01, 0.1, 1, 10, 100],
        'model__penalty': ['l2'],
        'model__solver': ['lbfgs', 'liblinear'],
        'model__max_iter': [100, 200, 500]
    },
    cv=5,
    scoring='accuracy',
    verbose=10,
    n_jobs=-1
)

In [12]:
grid_search_cv.fit(xtrain,ytrain)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 500 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=500).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('onehot_encoder',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         Index(['person_gender', 'person_home_ownership', 'loan_intent',
       'previous_loan_defaults_on_file'],
      dtype='str')),
                                                                        ('ordinal_encoder',
                                                                         OrdinalEncoder(categories=[['Master',
                                                                                                     'High '
                                                                                                     'School',
                                                                                                     'Bachelor',
                                                                                                     'Associate',
                                                                                                     'Doctorate']],
                                                                                        handle_unknown='use_encoded_value',
                                                                                        unknown_value=-1),
                                                                         ['person_education'])])),
                                       ('model',
                                        LogisticRegression(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__C': [0.01, 0.1, 1, 10, 100],
                         'model__max_iter': [100, 200, 500],
                         'model__penalty': ['l2'],
                         'model__solver': ['lbfgs', 'liblinear']},
             scoring='accuracy', verbose=10)

In [13]:
grid_search_cv.best_estimator_

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['person_gender', 'person_home_ownership', 'loan_intent',
       'previous_loan_defaults_on_file'],
      dtype='str')),
                                                 ('ordinal_encoder',
                                                  OrdinalEncoder(categories=[['Master',
                                                                              'High '
                                                                              'School',
                                                                              'Bachelor',
                                                                              'Associate',
                                                                              'Doctorate']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['person_education'])])),
                ('model',
                 LogisticRegression(C=0.01, max_iter=500, penalty='l2',
                                    random_state=42))])

In [14]:
grid_search_cv.best_params_

{'model__C': 0.01,
 'model__max_iter': 500,
 'model__penalty': 'l2',
 'model__solver': 'lbfgs'}

In [15]:
results=pd.DataFrame(grid_search_cv.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__C,param_model__max_iter,param_model__penalty,param_model__solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,4.024523,0.320939,0.229115,0.108231,0.01,100,l2,lbfgs,"{'model__C': 0.01, 'model__max_iter': 100, 'mo...",0.857639,0.870972,0.826667,0.866250,0.863194,0.856944,0.015746,12
1,2.464551,1.007180,0.136544,0.078722,0.01,100,l2,liblinear,"{'model__C': 0.01, 'model__max_iter': 100, 'mo...",0.791944,0.795000,0.885972,0.836667,0.833333,0.828583,0.034210,19
2,4.583789,0.221965,0.138283,0.028520,0.01,200,l2,lbfgs,"{'model__C': 0.01, 'model__max_iter': 200, 'mo...",0.883611,0.890278,0.874167,0.880972,0.870278,0.879861,0.007044,8
3,2.014892,0.600153,0.128880,0.036681,0.01,200,l2,liblinear,"{'model__C': 0.01, 'model__max_iter': 200, 'mo...",0.791944,0.795000,0.885972,0.836667,0.833333,0.828583,0.034210,19
4,17.269884,1.369116,0.418462,0.122598,0.01,500,l2,lbfgs,"{'model__C': 0.01, 'model__max_iter': 500, 'mo...",0.886250,0.889028,0.884861,0.883472,0.885139,0.885750,0.001863,1
5,2.817802,1.144258,0.195732,0.073357,0.01,500,l2,liblinear,"{'model__C': 0.01, 'model__max_iter': 500, 'mo...",0.791944,0.795000,0.885972,0.836667,0.833333,0.828583,0.034210,19
6,5.694790,2.336324,0.340531,0.212408,0.10,100,l2,lbfgs,"{'model__C': 0.1, 'model__max_iter': 100, 'mod...",0.827500,0.862917,0.846389,0.861667,0.862500,0.852194,0.013816,13
7,3.711394,0.387322,0.225301,0.139194,0.10,100,l2,liblinear,"{'model__C': 0.1, 'model__max_iter': 100, 'mod...",0.791944,0.795000,0.871528,0.836389,0.833611,0.825694,0.029526,22
8,6.372355,0.646601,0.104179,0.028935,0.10,200,l2,lbfgs,"{'model__C': 0.1, 'model__max_iter': 200, 'mod...",0.866806,0.885556,0.881389,0.876944,0.883056,0.878750,0.006599,9
9,2.837124,0.880783,0.147074,0.065903,0.10,200,l2,liblinear,"{'model__C': 0.1, 'model__max_iter': 200, 'mod...",0.791944,0.795000,0.871528,0.836389,0.833611,0.825694,0.029526,22
10,11.131490,0.471768,0.117521,0.025589,0.10,500,l2,lbfgs,"{'model__C': 0.1, 'model__max_iter': 500, 'mod...",0.885556,0.885833,0.885556,0.880139,0.883194,0.884056,0.002179,2
11,1.911051,0.558194,0.076457,0.011015,0.10,500,l2,liblinear,"{'model__C': 0.1, 'model__max_iter': 500, 'mod...",0.791944,0.795000,0.871528,0.836389,0.833611,0.825694,0.029526,22
12,2.877788,0.292680,0.132002,0.013852,1.00,100,l2,lbfgs,"{'model__C': 1, 'model__max_iter': 100, 'model...",0.858750,0.863333,0.850833,0.861667,0.863472,0.859611,0.004707,11
13,1.821949,0.411006,0.124742,0.014988,1.00,100,l2,liblinear,"{'model__C': 1, 'model__max_iter': 100, 'model...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
14,4.594002,0.123498,0.120840,0.032515,1.00,200,l2,lbfgs,"{'model__C': 1, 'model__max_iter': 200, 'model...",0.859028,0.885833,0.880139,0.877917,0.883472,0.877278,0.009521,10
15,1.800063,0.366661,0.143567,0.032056,1.00,200,l2,liblinear,"{'model__C': 1, 'model__max_iter': 200, 'model...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
16,13.702197,1.145438,0.296624,0.133306,1.00,500,l2,lbfgs,"{'model__C': 1, 'model__max_iter': 500, 'model...",0.885833,0.884583,0.884028,0.881111,0.882917,0.883694,0.001597,3
17,2.237746,0.654072,0.157485,0.074514,1.00,500,l2,liblinear,"{'model__C': 1, 'model__max_iter': 500, 'model...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
18,4.346932,1.162290,0.189131,0.076369,10.00,100,l2,lbfgs,"{'model__C': 10, 'model__max_iter': 100, 'mode...",0.857917,0.846111,0.828750,0.840833,0.841389,0.843000,0.009408,15
19,3.093149,0.440121,0.161726,0.129215,10.00,100,l2,liblinear,"{'model__C': 10, 'model__max_iter': 100, 'mode...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
20,5.498605,0.135508,0.115841,0.028897,10.00,200,l2,lbfgs,"{'model__C': 10, 'model__max_iter': 200, 'mode...",0.885139,0.885417,0.880833,0.878056,0.883333,0.882556,0.002781,6
21,2.354429,0.562697,0.097142,0.017238,10.00,200,l2,liblinear,"{'model__C': 10, 'model__max_iter': 200, 'mode...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
22,11.172259,0.263687,0.099640,0.026946,10.00,500,l2,lbfgs,"{'model__C': 10, 'model__max_iter': 500, 'mode...",0.885694,0.884583,0.883889,0.880278,0.883333,0.883556,0.001819,4
23,2.096099,0.477860,0.090844,0.008242,10.00,500,l2,liblinear,"{'model__C': 10, 'model__max_iter': 500, 'mode...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
24,2.592240,0.115023,0.097617,0.019390,100.00,100,l2,lbfgs,"{'model__C': 100, 'model__max_iter': 100, 'mod...",0.859028,0.835139,0.852917,0.851389,0.862361,0.852167,0.009403,14
25,1.966337,0.597320,0.476324,0.762041,100.00,100,l2,liblinear,"{'model__C': 100, 'model__max_iter': 100, 'mod...",0.791944,0.795000,0.886806,0.836389,0.833472,0.828722,0.034481,16
26,4.580719,0.622446,0.155195,0.032001,100.00,200,l2,lbfgs,"{'model__C': 100, 'model__max_iter': 200, 'mod...",0.885139,0.885417,0.880694,0.877222,0.883472,0.882389,0.003081,7
27,2.243056,0.715511,0.172599,0.088257,100.00,200,l2,liblinear,"{'model__C': 100, 'model__max_iter': 200, 'mod...",0.791944,0.795000,0.886806,0.836389,0.833472,0.828722,0.034481,16
28,10.482849,0.573983,0.062537,0.014775,100.00,500,l2,lbfgs,"{'model__C': 100, 'model__max_iter': 500, 'mod...",0.884444,0.884583,0.883889,0.880139,0.883056,0.883222,0.001633,5
29,3.099608,1.036803,0.190490,0.107766,100.00,500,l2,liblinear,"{'model__C': 100, 'model__max_iter': 500, 'mod...",0.791944,0.795000,0.886806,0.836389,0.833472,0.828722,0.034481,16

In [16]:
results.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__C,param_model__max_iter,param_model__penalty,param_model__solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
4,17.269884,1.369116,0.418462,0.122598,0.01,500,l2,lbfgs,"{'model__C': 0.01, 'model__max_iter': 500, 'mo...",0.886250,0.889028,0.884861,0.883472,0.885139,0.885750,0.001863,1
10,11.131490,0.471768,0.117521,0.025589,0.10,500,l2,lbfgs,"{'model__C': 0.1, 'model__max_iter': 500, 'mod...",0.885556,0.885833,0.885556,0.880139,0.883194,0.884056,0.002179,2
16,13.702197,1.145438,0.296624,0.133306,1.00,500,l2,lbfgs,"{'model__C': 1, 'model__max_iter': 500, 'model...",0.885833,0.884583,0.884028,0.881111,0.882917,0.883694,0.001597,3
22,11.172259,0.263687,0.099640,0.026946,10.00,500,l2,lbfgs,"{'model__C': 10, 'model__max_iter': 500, 'mode...",0.885694,0.884583,0.883889,0.880278,0.883333,0.883556,0.001819,4
28,10.482849,0.573983,0.062537,0.014775,100.00,500,l2,lbfgs,"{'model__C': 100, 'model__max_iter': 500, 'mod...",0.884444,0.884583,0.883889,0.880139,0.883056,0.883222,0.001633,5
20,5.498605,0.135508,0.115841,0.028897,10.00,200,l2,lbfgs,"{'model__C': 10, 'model__max_iter': 200, 'mode...",0.885139,0.885417,0.880833,0.878056,0.883333,0.882556,0.002781,6
26,4.580719,0.622446,0.155195,0.032001,100.00,200,l2,lbfgs,"{'model__C': 100, 'model__max_iter': 200, 'mod...",0.885139,0.885417,0.880694,0.877222,0.883472,0.882389,0.003081,7
2,4.583789,0.221965,0.138283,0.028520,0.01,200,l2,lbfgs,"{'model__C': 0.01, 'model__max_iter': 200, 'mo...",0.883611,0.890278,0.874167,0.880972,0.870278,0.879861,0.007044,8
8,6.372355,0.646601,0.104179,0.028935,0.10,200,l2,lbfgs,"{'model__C': 0.1, 'model__max_iter': 200, 'mod...",0.866806,0.885556,0.881389,0.876944,0.883056,0.878750,0.006599,9
14,4.594002,0.123498,0.120840,0.032515,1.00,200,l2,lbfgs,"{'model__C': 1, 'model__max_iter': 200, 'model...",0.859028,0.885833,0.880139,0.877917,0.883472,0.877278,0.009521,10
12,2.877788,0.292680,0.132002,0.013852,1.00,100,l2,lbfgs,"{'model__C': 1, 'model__max_iter': 100, 'model...",0.858750,0.863333,0.850833,0.861667,0.863472,0.859611,0.004707,11
0,4.024523,0.320939,0.229115,0.108231,0.01,100,l2,lbfgs,"{'model__C': 0.01, 'model__max_iter': 100, 'mo...",0.857639,0.870972,0.826667,0.866250,0.863194,0.856944,0.015746,12
6,5.694790,2.336324,0.340531,0.212408,0.10,100,l2,lbfgs,"{'model__C': 0.1, 'model__max_iter': 100, 'mod...",0.827500,0.862917,0.846389,0.861667,0.862500,0.852194,0.013816,13
24,2.592240,0.115023,0.097617,0.019390,100.00,100,l2,lbfgs,"{'model__C': 100, 'model__max_iter': 100, 'mod...",0.859028,0.835139,0.852917,0.851389,0.862361,0.852167,0.009403,14
18,4.346932,1.162290,0.189131,0.076369,10.00,100,l2,lbfgs,"{'model__C': 10, 'model__max_iter': 100, 'mode...",0.857917,0.846111,0.828750,0.840833,0.841389,0.843000,0.009408,15
25,1.966337,0.597320,0.476324,0.762041,100.00,100,l2,liblinear,"{'model__C': 100, 'model__max_iter': 100, 'mod...",0.791944,0.795000,0.886806,0.836389,0.833472,0.828722,0.034481,16
27,2.243056,0.715511,0.172599,0.088257,100.00,200,l2,liblinear,"{'model__C': 100, 'model__max_iter': 200, 'mod...",0.791944,0.795000,0.886806,0.836389,0.833472,0.828722,0.034481,16
29,3.099608,1.036803,0.190490,0.107766,100.00,500,l2,liblinear,"{'model__C': 100, 'model__max_iter': 500, 'mod...",0.791944,0.795000,0.886806,0.836389,0.833472,0.828722,0.034481,16
5,2.817802,1.144258,0.195732,0.073357,0.01,500,l2,liblinear,"{'model__C': 0.01, 'model__max_iter': 500, 'mo...",0.791944,0.795000,0.885972,0.836667,0.833333,0.828583,0.034210,19
1,2.464551,1.007180,0.136544,0.078722,0.01,100,l2,liblinear,"{'model__C': 0.01, 'model__max_iter': 100, 'mo...",0.791944,0.795000,0.885972,0.836667,0.833333,0.828583,0.034210,19
3,2.014892,0.600153,0.128880,0.036681,0.01,200,l2,liblinear,"{'model__C': 0.01, 'model__max_iter': 200, 'mo...",0.791944,0.795000,0.885972,0.836667,0.833333,0.828583,0.034210,19
7,3.711394,0.387322,0.225301,0.139194,0.10,100,l2,liblinear,"{'model__C': 0.1, 'model__max_iter': 100, 'mod...",0.791944,0.795000,0.871528,0.836389,0.833611,0.825694,0.029526,22
9,2.837124,0.880783,0.147074,0.065903,0.10,200,l2,liblinear,"{'model__C': 0.1, 'model__max_iter': 200, 'mod...",0.791944,0.795000,0.871528,0.836389,0.833611,0.825694,0.029526,22
11,1.911051,0.558194,0.076457,0.011015,0.10,500,l2,liblinear,"{'model__C': 0.1, 'model__max_iter': 500, 'mod...",0.791944,0.795000,0.871528,0.836389,0.833611,0.825694,0.029526,22
15,1.800063,0.366661,0.143567,0.032056,1.00,200,l2,liblinear,"{'model__C': 1, 'model__max_iter': 200, 'model...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
13,1.821949,0.411006,0.124742,0.014988,1.00,100,l2,liblinear,"{'model__C': 1, 'model__max_iter': 100, 'model...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
17,2.237746,0.654072,0.157485,0.074514,1.00,500,l2,liblinear,"{'model__C': 1, 'model__max_iter': 500, 'model...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
19,3.093149,0.440121,0.161726,0.129215,10.00,100,l2,liblinear,"{'model__C': 10, 'model__max_iter': 100, 'mode...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
23,2.096099,0.477860,0.090844,0.008242,10.00,500,l2,liblinear,"{'model__C': 10, 'model__max_iter': 500, 'mode...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25
21,2.354429,0.562697,0.097142,0.017238,10.00,200,l2,liblinear,"{'model__C': 10, 'model__max_iter': 200, 'mode...",0.791944,0.795000,0.871528,0.836389,0.833472,0.825667,0.029519,25